# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Python\Projekter\ALPDF\GUI\ALPDF.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets
from PyQt6.QtWidgets import QStatusBar, QToolBar, QWidget
from PyQt6.QtGui import QAction
from PyQt6.QtWebEngineWidgets import QWebEngineView

class Ui_MenuMain(object):
    def setupUi(self, MenuMain):
        MenuMain.setObjectName("MenuMain")
        MenuMain.resize(912, 771)
        self.centralwidget = QWidget(MenuMain)
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.wevPDF = QWebEngineView(self.centralwidget)
        self.wevPDF.setGeometry(QtCore.QRect(10, 60, 881, 621))
        self.wevPDF.setUrl(QtCore.QUrl("about:blank"))
        self.wevPDF.setObjectName("wevPDF")
        MenuMain.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MenuMain)
        self.statusbar.setObjectName("statusbar")
        MenuMain.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MenuMain)
        self.toolBar.setObjectName("toolBar")
        MenuMain.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.actionOpen = QAction(MenuMain)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QAction(MenuMain)
        self.actionClose.setObjectName("actionClose")
        self.actionSaveAs = QAction(MenuMain)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionMerge = QAction(MenuMain)
        self.actionMerge.setObjectName("actionMerge")
        self.actionPrint = QAction(MenuMain)
        self.actionPrint.setObjectName("actionPrint")
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSaveAs)
        self.toolBar.addAction(self.actionClose)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionMerge)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPrint)

        self.retranslateUi(MenuMain)
        QtCore.QMetaObject.connectSlotsByName(MenuMain)

    def retranslateUi(self, MenuMain):
        _translate = QtCore.QCoreApplication.translate
        MenuMain.setWindowTitle(_translate("MenuMain", "MainWindow"))
        self.toolBar.setWindowTitle(_translate("MenuMain", "toolBar"))
        self.actionOpen.setText(_translate("MenuMain", "Open"))
        self.actionOpen.setStatusTip(_translate("MenuMain", "Open document"))
        self.actionClose.setText(_translate("MenuMain", "Close"))
        self.actionClose.setStatusTip(_translate("MenuMain", "Close current document"))
        self.actionSaveAs.setText(_translate("MenuMain", "Save as..."))
        self.actionSaveAs.setStatusTip(_translate("MenuMain", "Save current document as..."))
        self.actionMerge.setText(_translate("MenuMain", "Merge"))
        self.actionPrint.setText(_translate("MenuMain", "Print"))
        self.actionPrint.setStatusTip(_translate("MenuMain", "Print current document"))
# from PyQt5 import QtWebEngineWidgets
